version: "3.8"

services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sim-aha

        restart: always
        working_dir: /var/www/html
        volumes:
            - /var/project/sim-aha:/var/www/html
            - /var/project/sim-aha/storage:/var/www/html/storage
            - backup_data:/var/www/html/backup
        ports:
            - "9900:80"
        networks:
            - sim-aha_network

networks:
    sim-aha_network:
        external: true

volumes:
    backup_data: